---
- name: Configure web server
  hosts: "{{ myserver | default('localhost') }}"
  tasks:

    - name: include environment tasks
      ansible.builtin.include_tasks: 
        environment.yml
      vars:
         package: httpd
         service: httpd

    - name: include firewall tasks
      ansible.builtin.include_tasks:
        firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule:
          - http
          - https

    - name: include placeholder tasks
      ansible.builtin.import_tasks:
        placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: Test url with a different play
  ansible.builtin.import_playbook:
    PlayTest.yml
  vars:
    url: http://myserver
