- name: Play - Testing controls
  hosts: "{{ myhost | default('localhost') }}"
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Block install web package
      block:
        - name: run command module to capture date
          changed_when: false
          ansible.builtin.command: date
          register: command_result

        - name: Debug variable
          ansible.builtin.debug:
            msg: "{{ command_result.stdout }}"

        - name: Install web package software
          failed_when:  web_package  == "httpd"
          ansible.builtin.dnf:
            name: "{{ web_package }}"
            state: present

      rescue:

        - name: Install DB packages
          ansible.builtin.dnf:
            name: "{{ db_package }}"
            state: present
      
      always:

        - name: Start service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started
            enabled: yes
